<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Luxembourg_hasVisited</name>
   <tag></tag>
   <elementGuidId>14f660cd-e794-4ae8-aaac-c44b5a4035dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='countries']/tbody/tr[104]/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc20deeb-33aa-48bf-86b3-092437b9e23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hasVisited</value>
      <webElementGuid>105e5305-3ccb-4838-8d9b-a4ee33799077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a6c46137-040b-43fd-80b7-47baada62f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countries&quot;)/tbody[1]/tr[104]/td[1]/input[@class=&quot;hasVisited&quot;]</value>
      <webElementGuid>2e27d0d6-2521-4591-b91a-3dceb14e1e96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[103]</value>
      <webElementGuid>fed9404e-8809-449e-b99b-efcabaec3c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='countries']/tbody/tr[104]/td/input</value>
      <webElementGuid>b014caaa-854b-40ae-909e-81e81fbe3e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[104]/td/input</value>
      <webElementGuid>e0087b73-7e18-4ad5-b650-b82481f111ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>c72ab241-14b3-410d-bda1-d70afa467cba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
